version: "3.9"

services:
  qiitadocc:
    container_name: qiitadocc
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/workspace:delegated
      - node_modules:/workspace/node_modules
    ports:
      - 8009:8000
    restart: always

volumes:
  node_modules:
